// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// waveft
NumericMatrix waveft(NumericVector omega, NumericVector scales);
RcppExport SEXP _MAPD_waveft(SEXP omegaSEXP, SEXP scalesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type scales(scalesSEXP);
    rcpp_result_gen = Rcpp::wrap(waveft(omega, scales));
    return rcpp_result_gen;
END_RCPP
}
// cwtft
List cwtft(NumericVector val, NumericVector scales);
RcppExport SEXP _MAPD_cwtft(SEXP valSEXP, SEXP scalesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type val(valSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type scales(scalesSEXP);
    rcpp_result_gen = Rcpp::wrap(cwtft(val, scales));
    return rcpp_result_gen;
END_RCPP
}
// localMax
LogicalMatrix localMax(NumericMatrix cwt2d);
RcppExport SEXP _MAPD_localMax(SEXP cwt2dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type cwt2d(cwt2dSEXP);
    rcpp_result_gen = Rcpp::wrap(localMax(cwt2d));
    return rcpp_result_gen;
END_RCPP
}
// localMin
LogicalMatrix localMin(NumericMatrix cwt2d);
RcppExport SEXP _MAPD_localMin(SEXP cwt2dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type cwt2d(cwt2dSEXP);
    rcpp_result_gen = Rcpp::wrap(localMin(cwt2d));
    return rcpp_result_gen;
END_RCPP
}
// ridgesDetection
List ridgesDetection(NumericMatrix cwt2d, NumericVector val);
RcppExport SEXP _MAPD_ridgesDetection(SEXP cwt2dSEXP, SEXP valSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type cwt2d(cwt2dSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type val(valSEXP);
    rcpp_result_gen = Rcpp::wrap(ridgesDetection(cwt2d, val));
    return rcpp_result_gen;
END_RCPP
}
// peaksPosition
NumericVector peaksPosition(NumericVector val, List ridges, NumericMatrix cwt2d);
RcppExport SEXP _MAPD_peaksPosition(SEXP valSEXP, SEXP ridgesSEXP, SEXP cwt2dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type val(valSEXP);
    Rcpp::traits::input_parameter< List >::type ridges(ridgesSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type cwt2d(cwt2dSEXP);
    rcpp_result_gen = Rcpp::wrap(peaksPosition(val, ridges, cwt2d));
    return rcpp_result_gen;
END_RCPP
}
// getSignal
List getSignal(NumericMatrix cwt2d, List ridges, NumericVector peaks);
RcppExport SEXP _MAPD_getSignal(SEXP cwt2dSEXP, SEXP ridgesSEXP, SEXP peaksSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type cwt2d(cwt2dSEXP);
    Rcpp::traits::input_parameter< List >::type ridges(ridgesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type peaks(peaksSEXP);
    rcpp_result_gen = Rcpp::wrap(getSignal(cwt2d, ridges, peaks));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MAPD_waveft", (DL_FUNC) &_MAPD_waveft, 2},
    {"_MAPD_cwtft", (DL_FUNC) &_MAPD_cwtft, 2},
    {"_MAPD_localMax", (DL_FUNC) &_MAPD_localMax, 1},
    {"_MAPD_localMin", (DL_FUNC) &_MAPD_localMin, 1},
    {"_MAPD_ridgesDetection", (DL_FUNC) &_MAPD_ridgesDetection, 2},
    {"_MAPD_peaksPosition", (DL_FUNC) &_MAPD_peaksPosition, 3},
    {"_MAPD_getSignal", (DL_FUNC) &_MAPD_getSignal, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_MAPD(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
