# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

waveft <- function(omega, scales) {
    .Call(`_MAPD_waveft`, omega, scales)
}

cwtft <- function(val, scales) {
    .Call(`_MAPD_cwtft`, val, scales)
}

localMax <- function(cwt2d) {
    .Call(`_MAPD_localMax`, cwt2d)
}

localMin <- function(cwt2d) {
    .Call(`_MAPD_localMin`, cwt2d)
}

ridgesDetection <- function(cwt2d, val) {
    .Call(`_MAPD_ridgesDetection`, cwt2d, val)
}

peaksPosition <- function(val, ridges, cwt2d) {
    .Call(`_MAPD_peaksPosition`, val, ridges, cwt2d)
}

getSignal <- function(cwt2d, ridges, peaks) {
    .Call(`_MAPD_getSignal`, cwt2d, ridges, peaks)
}

